//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouses
    {
        public int id { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<int> ingredient_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual ingredients ingredients { get; set; }
        public virtual stores stores { get; set; }
    }
}
